name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository with playwright tests
      uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: Checkout external repository with test-app project
      uses: actions/checkout@v4
      with:
        repository: "gomczak/test-app"
        path: "test-app"
        ref: update-docker-compose
    - name: Run docker compose
      env:
        MONGODB_URI: ${{secrets.MONGODB_URI}}
        PORT: 3000
      run: |
        cd test-app
        docker compose up --build
    - name: Install dependencies
      run: npm install -g pnpm && pnpm install
    - name: Install Playwright Browsers
      run: pnpm exec playwright install --with-deps
    - name: Run Playwright tests
      run: pnpm exec playwright test
    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
